import type { Metadata } from "next";
import '../app/styles/globals.css'
import Header from '@/components/header';
import Bottom from '@/components/bottom';


export const metadata: Metadata = {
  title: "Rogovski",
  description: "Generated by create next app",
};

/*
export default function Layout({ 
  children }: { children: React.ReactNode }) {  
*/

export default function RootLayout({ 
  children,
 }: Readonly<{ 
  children: React.ReactNode;
 }>) {  

  return (
    <html lang="en"> {/* Define the <html> tag with language */}
      <body>
        <main>
        {children} {/* This is where the content of your pages will appear */}
        </main>
      </body>
    </html>

  );
};