import type { Metadata } from "next";
import './styles/global.css'


export const metadata: Metadata = {
  title: "Rogovski",
  description: "Generated by create next app",
  keywords: ['Rogovski', 'RussianRestaurant'],
  authors: [
    { name: 'Vlad', url: ''}
  ]
};


export default function RootLayout({ 
  children,
 }: Readonly<{ 
  children: React.ReactNode;
 }>) {  

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>{children}</body>
    </html>

  );
};